// web/src/pages/LoginPage.vue
<script setup lang="ts">
import { onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { setToken } from '@/lib/auth'

const router = useRouter()

const authMode = import.meta.env.VITE_AUTH_MODE as string | undefined
const envToken = import.meta.env.VITE_API_TOKEN as string | undefined

onMounted(() => {
  // In token mode, auto-login with the env token — no GitHub OAuth needed.
  if (authMode === 'token' && envToken) {
    setToken(envToken)
    router.replace('/')
  }
})

function loginWithGitHub() {
  window.location.href = `${import.meta.env.VITE_API_URL || 'http://localhost:8080'}/api/auth/github/login`
}
</script>

<template>
  <div class="min-h-screen flex items-center justify-center bg-bg-primary p-8">
    <div class="bg-bg-card border-5 border-ink shadow-hard-xl p-10 max-w-md w-full text-center">
      <h1 class="font-display font-black text-5xl uppercase tracking-tight mb-2">
        Dev<span class="bg-accent-pink px-2 border-3 border-ink">Deck</span>
      </h1>
      <p class="font-mono text-sm text-ink-soft mb-8">
        Tu colección de repos, comandos y cheatsheets.
      </p>

      <div class="w-20 h-20 mx-auto mb-6 border-3 border-ink bg-accent-lime flex items-center justify-center text-3xl">
        🦎
      </div>

      <!-- Token mode: show loading while auto-redirecting -->
      <div v-if="authMode === 'token'" class="font-mono text-sm text-ink-soft">
        Cargando…
      </div>

      <!-- JWT mode: GitHub OAuth -->
      <button
        v-else
        @click="loginWithGitHub"
        class="w-full border-3 border-ink bg-ink text-white font-display font-bold uppercase
               text-lg py-4 px-6 shadow-hard
               hover:-translate-x-1 hover:-translate-y-1 hover:shadow-hard-lg
               active:translate-x-1 active:translate-y-1 active:shadow-hard-sm
               transition-all duration-150 flex items-center justify-center gap-3"
      >
        <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 24 24"><path d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385.6.105.825-.255.825-.57 0-.285-.015-1.23-.015-2.235-3.015.555-3.795-.735-4.035-1.41-.135-.345-.72-1.41-1.23-1.695-.42-.225-1.02-.78-.015-.795.945-.015 1.62.87 1.845 1.23 1.08 1.815 2.805 1.305 3.495.99.105-.78.42-1.305.765-1.605-2.67-.3-5.46-1.335-5.46-5.925 0-1.305.465-2.385 1.23-3.225-.12-.3-.54-1.53.12-3.18 0 0 1.005-.315 3.3 1.23.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23.66 1.65.24 2.88.12 3.18.765.84 1.23 1.905 1.23 3.225 0 4.605-2.805 5.625-5.475 5.925.435.375.81 1.095.81 2.22 0 1.605-.015 2.895-.015 3.3 0 .315.225.69.825.57A12.02 12.02 0 0024 12c0-6.63-5.37-12-12-12z"/></svg>
        Sign in with GitHub
      </button>

      <p class="font-mono text-xs text-ink-soft mt-6">
        Solo necesitamos tu perfil público.
      </p>
    </div>
  </div>
</template>

// apps/desktop/src/renderer/src/pages/LoginPage.tsx
import { useEffect, useState } from 'react'
import { useNavigate, Link, useSearchParams } from 'react-router-dom'
import { Apple, Chrome, Github, Loader2 } from 'lucide-react'
import { fetchAuthProviders, loginLocal, setTokens, type AuthProviderInfo } from '@devdeck/api-client'

export function LoginPage() {
  const navigate = useNavigate()
  const [searchParams] = useSearchParams()
  const [providers, setProviders] = useState<AuthProviderInfo[]>([])
  const [loadError, setLoadError] = useState<string | null>(null)
  
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [loginError, setLoginError] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)

  const authMode = import.meta.env.VITE_AUTH_MODE
  const envToken = import.meta.env.VITE_API_TOKEN
  const apiUrl = import.meta.env.VITE_API_URL || 'http://localhost:8080'
  const isVerified = searchParams.get('verified') === 'true'
  const isResetSuccess = searchParams.get('reset') === 'success'

  useEffect(() => {
    if (authMode === 'token' && envToken) {
      setTokens(envToken, envToken)
      navigate('/', { replace: true })
      return
    }
    fetchAuthProviders()
      .then((next) => {
        setProviders(next)
        setLoadError(null)
      })
      .catch((err: unknown) => {
        setLoadError(err instanceof Error ? err.message : 'No se pudieron cargar los proveedores.')
      })
  }, [authMode, envToken, navigate])

  async function handleLogin(e: React.FormEvent) {
    e.preventDefault()
    setLoading(true)
    setLoginError(null)
    try {
      await loginLocal(email, password)
      navigate('/', { replace: true })
    } catch (err: any) {
      setLoginError(err.message || 'Error al iniciar sesión')
    } finally {
      setLoading(false)
    }
  }

  function startLogin(provider: AuthProviderInfo['provider']) {
    const url = `${apiUrl}/api/auth/${provider}/login?device=desktop`
    window.electronAPI?.auth.openExternal(url)
  }

  function providerIcon(provider: AuthProviderInfo['provider']) {
    switch (provider) {
      case 'github':
        return <Github size={20} strokeWidth={2.5} />
      case 'google':
        return <Chrome size={20} strokeWidth={2.5} />
      case 'apple':
        return <Apple size={20} strokeWidth={2.5} />
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-bg-primary p-8">
      <div className="bg-bg-card border-5 border-ink shadow-hard-xl p-10 max-w-md w-full text-center">
        <h1 className="font-display font-black text-5xl uppercase tracking-tight mb-2">
          Dev
          <span className="bg-accent-pink px-2 border-3 border-ink">Deck</span>
        </h1>
        <p className="font-mono text-sm text-ink-soft mb-8">
          Tu memoria externa para desarrollo.
        </p>

        {isVerified && (
          <div className="border-3 border-ink bg-accent-lime px-4 py-2 font-mono text-xs mb-6 shadow-hard">
            Email verificado correctamente. ¡Ya podés entrar!
          </div>
        )}

        {isResetSuccess && (
          <div className="border-3 border-ink bg-accent-lime px-4 py-2 font-mono text-xs mb-6 shadow-hard">
            Contraseña actualizada. ¡Ya podés entrar con la nueva!
          </div>
        )}

        {loginError && (
          <div className="border-3 border-ink bg-accent-yellow px-4 py-2 font-mono text-xs mb-6 shadow-hard">
            {loginError}
          </div>
        )}

        <form onSubmit={handleLogin} className="space-y-4 mb-8 text-left">
          <div>
            <label className="block font-display font-bold uppercase text-xs mb-1 ml-1">Email</label>
            <input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
              className="w-full border-3 border-ink bg-bg-primary px-4 py-3 font-mono text-sm focus:outline-none focus:bg-white shadow-hard-sm"
              placeholder="tu@email.com"
            />
          </div>
          <div>
            <label className="block font-display font-bold uppercase text-xs mb-1 ml-1">Contraseña</label>
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
              className="w-full border-3 border-ink bg-bg-primary px-4 py-3 font-mono text-sm focus:outline-none focus:bg-white shadow-hard-sm"
              placeholder="••••••••"
            />
          </div>
          <button
            type="submit"
            disabled={loading}
            className="w-full border-3 border-ink bg-accent-cyan text-white font-display font-bold uppercase
                       text-lg py-4 shadow-hard hover:-translate-x-1 hover:-translate-y-1 hover:shadow-hard-lg
                       active:translate-x-0.5 active:translate-y-0.5 active:shadow-hard-sm
                       transition-all duration-150 flex items-center justify-center gap-2"
          >
            {loading ? <Loader2 className="animate-spin" /> : 'Entrar'}
          </button>
          
          <div className="flex justify-between font-mono text-[10px] uppercase font-bold px-1">
            <Link to="/forgot-password" title="recuperar" className="hover:underline">¿Olvidaste tu contraseña?</Link>
            <Link to="/register" title="registro" className="text-accent-pink hover:underline">Crear cuenta</Link>
          </div>
        </form>

        <div className="relative mb-8">
          <div className="absolute inset-0 flex items-center"><span className="w-full border-t-2 border-ink-soft"></span></div>
          <div className="relative flex justify-center text-xs uppercase"><span className="bg-bg-card px-3 font-mono font-bold text-ink-soft">o continuar con</span></div>
        </div>

        {authMode === 'token' ? (
          <div className="font-mono text-sm text-ink-soft">Cargando…</div>
        ) : loadError ? (
          <div className="border-3 border-ink bg-accent-yellow px-4 py-3 font-mono text-sm">
            {loadError}
          </div>
        ) : (
          <div className="grid grid-cols-3 gap-3">
            {providers.map((provider) => (
              <button
                key={provider.provider}
                type="button"
                onClick={() => startLogin(provider.provider)}
                className="border-3 border-ink bg-white p-3 shadow-hard
                           hover:-translate-x-1 hover:-translate-y-1 hover:shadow-hard-lg
                           active:translate-x-0.5 active:translate-y-0.5 active:shadow-hard-sm
                           transition-all duration-150 flex items-center justify-center"
                title={`Entrar con ${provider.label}`}
              >
                {providerIcon(provider.provider)}
              </button>
            ))}
          </div>
        )}
      </div>
    </div>
  )
}
